version: '3'

services:
  app:
    build: .
    restart: always
    container_name: 'movies-app'
    ports:
      - '5000:8080'
    env_file:
      - env/app.env
    depends_on:
      - db

  db:
    image: mongo
    container_name: 'movies-db'
    env_file:
      - env/db.env
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d
